language: android
jdk: oraclejdk8
android:
        components:
                - platform-tools
                - build-tools-28.0.3
                - android-28
script:
        - ./gradlew build
        - ./gradlew test
        - ./gradlew build jacocoTestReport
before_install:
        - chmod +x gradlew
branches:
        only:
                - master
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 46172f04-1921-47f0-b0c3-b95c8afdba70
